-- Save this as 04_headphones_speakers.sql
USE electronics_db;

-- Headphones & Speakers Products (next 7 products)
INSERT INTO products (sku, name, slug, brand_id, category_id, description, short_description, price, compare_at_price, stock_quantity, specs, warranty_period, is_featured, status, weight, dimensions) VALUES
('SONY-WH1000XM5-BLK', 'Sony WH-1000XM5 Wireless Headphones', 'sony-wh-1000xm5-wireless-headphones', 3, 2, 'Industry-leading noise cancellation...', 'Premium noise-canceling headphones', 399.99, 449.99, 58, '{"driver": "30mm", "frequency_response": "4-40,000 Hz", "battery": "30 hours (ANC on)", "charging": "3 hours (10 min = 3 hours playback)", "connectivity": "Bluetooth 5.2, NFC, 3.5mm", "noise_cancellation": "Yes, Adaptive Sound Control", "microphones": "8 total", "features": "Speak-to-Chat, Quick Attention, DSEE Extreme", "weight": "250g", "foldable": "Yes"}', 24, 1, 'active', 0.250, '[21.0, 16.5, 8.0]'),

('BOSE-QC45-BLACK', 'Bose QuietComfort 45 Wireless Headphones', 'bose-quietcomfort-45-wireless', 7, 2, 'Legendary comfort meets advanced noise cancellation...', 'Comfortable noise-canceling headphones', 329.99, 379.99, 42, '{"driver": "40mm", "frequency_response": "20-20,000 Hz", "battery": "24 hours", "charging": "15 min = 2.5 hours playback", "connectivity": "Bluetooth 5.1", "noise_cancellation": "Yes (Quiet and Aware Modes)", "microphones": "4 total", "features": "TriPort architecture, Volume-optimized EQ", "weight": "240g", "foldable": "Yes"}', 24, 1, 'active', 0.240, '[18.0, 17.0, 7.5]'),

('AIRPODS-PRO2-WHITE', 'Apple AirPods Pro (2nd Generation)', 'apple-airpods-pro-2nd-gen', 1, 2, 'Next-generation AirPods Pro with H2 chip...', 'Premium wireless earbuds with ANC', 249.99, 279.99, 95, '{"driver": "Custom high-excursion driver", "battery": "6 hours (ANC on), 30 hours with case", "charging": "MagSafe, Qi, Lightning", "connectivity": "Bluetooth 5.3", "noise_cancellation": "Adaptive Transparency and ANC", "features": "Personalized Spatial Audio, Find My, Skin Detection", "water_resistance": "IPX4 (earbuds and case)", "case": "MagSafe Charging Case with speaker"}', 12, 1, 'active', 0.045, '[2.13, 2.13, 0.94]'),

('JBL-FLIP6-BLUE', 'JBL Flip 6 Portable Speaker', 'jbl-flip-6-portable-speaker', 8, 2, 'Portable Bluetooth speaker with deep bass...', 'Waterproof portable Bluetooth speaker', 129.99, 149.99, 78, '{"power": "30W RMS", "battery": "12 hours playback", "charging": "USB-C (cable included)", "connectivity": "Bluetooth 5.1", "water_resistance": "IP67 (waterproof and dustproof)", "features": "PartyBoost, JBL Pro Sound, Speakerphone", "weight": "550g", "colors": "Black, Blue, Red, Green, Gray"}', 12, 0, 'active', 0.550, '[17.8, 6.9, 7.2]'),

('BOSE-HOME500-BLACK', 'Bose Home Speaker 500', 'bose-home-speaker-500', 7, 2, 'Smart speaker with powerful stereo sound...', 'Smart home speaker with Alexa', 299.99, 349.99, 32, '{"power": "Not specified", "connectivity": "Wi-Fi, Bluetooth, Apple AirPlay 2", "voice_assistant": "Alexa and Google Assistant built-in", "features": "Stereo sound, LCD display, 6 presets", "dimensions": "20.3 x 13.7 x 10.2 cm", "weight": "2.2 kg", "colors": "Black, White", "audio_input": "3.5mm AUX"}', 24, 0, 'active', 2.200, '[20.3, 13.7, 10.2]'),

('SONY-WF1000XM5-BLK', 'Sony WF-1000XM5 Wireless Earbuds', 'sony-wf-1000xm5-wireless-earbuds', 3, 2, 'Premium true wireless earbuds...', 'Premium wireless earbuds with ANC', 299.99, 349.99, 62, '{"driver": "8.4mm", "battery": "8 hours (ANC on), 24 hours with case", "charging": "Qi wireless, USB-C", "connectivity": "Bluetooth 5.3 with LE Audio, LDAC", "noise_cancellation": "Yes, with Adaptive Sound Control", "water_resistance": "IPX4", "features": "Multipoint connection, Speak-to-Chat, Hi-Res Audio", "weight": "5.9g per earbud", "case_weight": "39g"}', 24, 1, 'active', 0.044, '[2.5, 2.0, 2.1]'),

('JBL-CHARGE5-CAMO', 'JBL Charge 5 Portable Speaker', 'jbl-charge-5-portable-speaker', 8, 2, 'Portable Bluetooth speaker with powerful sound...', 'Portable speaker with power bank', 179.99, 199.99, 45, '{"power": "Not specified", "battery": "20 hours playback", "power_bank": "Yes (can charge devices)", "charging": "USB-C", "connectivity": "Bluetooth 5.1", "water_resistance": "IP67", "features": "PartyBoost, JBL Pro Sound, Power bank", "weight": "960g", "colors": "Black, Blue, Red, Camo, Squad"}', 12, 0, 'active', 0.960, '[22.3, 9.5, 9.3]');